PROG = tagutil

#CFLAGS  += -g -Wall -std=c89 -pedantic -D_XOPEN_SOURCE=500 # dev flags
CFLAGS  += -std=c99 -Wall -O2 -pipe -D_XOPEN_SOURCE=500
LDFLAGS += -ltag_c

clean:
	@rm $(PROG) &>/dev/null || true
tags: $(PROG).c
	ctags $(PROG).c
