#ifndef T_TAGUTIL_H
#define T_TAGUTIL_H


#include <stdio.h>
#include <stdbool.h>
#include <taglib/tag_c.h>

#include "config.h"


/*
 * you should not modifiy them, eval_tag() implementation might be depend.
 */
#define kTITLE      "%t"
#define kALBUM      "%a"
#define kARTIST     "%A"
#define kYEAR       "%y"
#define kTRACK      "%T"
#define kCOMMENT    "%c"
#define kGENRE      "%g"


/*
 * tagutil_f is the type of function that implement actions in tagutil.
 * 1rst arg: the current file's name
 * 2nd  arg: the TagLib_File of the current file
 * 3rd  arg: the arg supplied to the action (for example, if -y is given as
 * option then action is tagutil_year and arg is the new value for the
 * year tag.
 */
typedef bool (*tagutil_f)(const char *restrict, TagLib_File *restrict, const void *restrict);

/**********************************************************************/


/*
 * show usage and exit.
 */
void usage(void) __attribute__ ((__noreturn__));


/* FILE FUNCTIONS */

/*
 * rename path to new_path. err(3) if new_path already exist.
 */
void safe_rename(const char *restrict oldpath, const char *restrict newpath)
    __attribute__ ((__nonnull__ (1, 2)));


/*
 * create a temporary file in $TMPDIR. if $TMPDIR is not set, /tmp is
 * used. return the full path to the temp file created.
 *
 * returned value has to be freed.
 */
char* create_tmpfile(void);


/* TAG FUNCTIONS */

/*
 * return a char* that contains all tag infos.
 *
 * returned value has to be freed.
 */
char* printable_tag(const TagLib_Tag *restrict tag)
    __attribute__ ((__nonnull__ (1)));


/*
 * call "$EDITOR path" (the environment variable $EDITOR must be set).
 */
bool user_edit(const char *restrict path)
    __attribute__ ((__nonnull__ (1)));


/*
 * read fp and tag. the format of the text should bethe same as tagutil_print.
 * return false if a line can't be parsed, true if all went smoothly.
 */
bool update_tag(TagLib_Tag *restrict tag, FILE *restrict fp)
    __attribute__ ((__nonnull__(1, 2)));


/*
 * replace each tagutil keywords by their value. see k* keywords.
 */
char* eval_tag(const char *restrict pattern, const TagLib_Tag *restrict tag)
    __attribute__ ((__nonnull__(1, 2)));

/* TAGUTIL FUNCTIONS */

/*
 * print the given file's tag to stdin.
 */
bool tagutil_print(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2)));


/*
 * print the given file's tag and prompt to ask if tag edit is needed. if
 * answer is yes create a tempfile, fill is with infos, run $EDITOR, then
 * parse the tempfile and update the file's tag.
 */
bool tagutil_edit(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2)));


/*
 * rename the file at path with the given pattern arg. the pattern can use
 * some keywords for tags (see usage()).
 */
bool tagutil_rename(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));

/*
 * print given path if the file match the given ast (arg).
 */
bool tagutil_filter(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));

/* functions below are generated by the _MAKE_TAGUTIL_FUNC macro. */
/* FIXME: this macro is ugly. should just write them all */
bool tagutil_title(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_album(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_artist(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_year(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_track(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_comment(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));
bool tagutil_genre(const char *restrict path, TagLib_File *restrict f, const void *restrict arg)
    __attribute__ ((__nonnull__ (1, 2, 3)));


#endif /* not T_TAGUTIL_H */
