diff -r 4f0d58c6b736 Makefile
--- a/Makefile	Thu Nov 13 10:38:41 2008 +0100
+++ b/Makefile	Thu Nov 13 11:24:34 2008 +0100
@@ -6,11 +6,20 @@
 DESTDIR		 = ${PREFIX}
 
 CSTD		 = c99
-LDADD		 = -L/usr/local/lib -ltag_c
+LDADD		 = -ltag_c
 
-CFLAGS		+= -Wall -I/usr/local/include/
+GLUEFLAGS	 = -DT_INSANE_DIRNAME \
+			   -DT_LACK_OF_GETPROGNAME \
+			   -DT_NO_DEV
+CFLAGS		+= -Wall -D_XOPEN_SOURCE=500 -std=${CSTD} ${GLUEFLAGS}
+LDFLAGS		+= ${LDADD}
+
+all: ${SRCS:%.c=%.o}
+	${CC} -o ${PROG} ${LDFLAGS} $+
+
+clean:
+	-rm -f ${PROG} ${SRCS:%.c=%.o}
 
 depends:
 	@${CC} -E -MM ${SRCS} > .depend
 
-.include <bsd.prog.mk>
